### PR TITLE
added a new plugin to plot the states of the residents and guests in …

### PR DESCRIPTION
**Pull request by Zephyr82**
…a graph

### CODE REVIEW

**Comment by solexx** [comment]
Thanks, again! Can you also add a line to README.md for this plugin?

**Comment by Zephyr82** [comment]
I added the description in README.md in the branch `resident_state`.
I should also add a plugin description for the `battery_percentage` plugin, shouldn't I? May I do that in the master branch and open another pull request?

**Comment by solexx** [comment]
Sounds fine with me! (I am not that proficient with Git yet ...)

**Comment by Zephyr82** [comment]
I'm not either. Just learning by doing. :)

**Pull request merged**
